version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: ezyskills-db
    environment:
      POSTGRES_DB: ezyskills
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ezyskills-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  db-data:
