spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ezyskills
    username: postgres
    password: 123
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
  flyway:
    baseline-on-migrate: true

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
