spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ezyskills
    username: postgres
    password: 123
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
  flyway:
    baseline-on-migrate: true


  mail:
    host: smtp.yandex.com
    port: 465
    username: ezyskills@yandex.ru
    password: "icxbssfrpmxudwcd"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        debug: true

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG

support:
  email: ezyskills@yandex.ru