spring:
  application:
    name: diplom
    courses:
      page-size: 9
      sort-default: newest

  data:
    web:
      pageable:
        default-page-size: 9
        max-page-size: 50

  main:
    banner-mode: off
    allow-bean-definition-overriding: true

  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.flywaydb: DEBUG

support:
  email: ezyskills@yandex.ru