spring:
  application:
    name: diplom

  main:
    banner-mode: off
    allow-bean-definition-overriding: true

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/ezyskills
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.yandex.com
    port: 465
    username: ezyskills@yandex.ru
    password: "icxbssfrpmxudwcd"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

support:
  email: ezyskills@yandex.ru
