spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    clean-disabled: false
    locations: classpath:db/test_migration
